// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/auth.dart';
import 'api/flarum.dart';
import 'api/misskey.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 237017943;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiFlarumFlarumRustClientClearToken({
    required FlarumRustClient that,
  });

  Future<String> crateApiFlarumFlarumRustClientGet({
    required FlarumRustClient that,
    required String path,
  });

  FlarumRustClient crateApiFlarumFlarumRustClientNew({required String baseUrl});

  Future<String> crateApiFlarumFlarumRustClientPost({
    required FlarumRustClient that,
    required String path,
    required String bodyJson,
  });

  Future<void> crateApiFlarumFlarumRustClientSetToken({
    required FlarumRustClient that,
    required String token,
    String? userId,
  });

  Future<String> crateApiAuthJuheAuthClientCallbackAuth({
    required JuheAuthClient that,
    required String code,
  });

  Future<String> crateApiAuthJuheAuthClientGetLoginUrl({
    required JuheAuthClient that,
    required String type,
    required String state,
  });

  JuheAuthClient crateApiAuthJuheAuthClientNew({
    required String appid,
    required String appkey,
    required String apiurl,
    required String callback,
  });

  Future<String> crateApiAuthJuheAuthClientQueryUser({
    required JuheAuthClient that,
    required String type,
    required String socialUid,
  });

  Future<String> crateApiMisskeyMisskeyRustClientCreateNote({
    required MisskeyRustClient that,
    String? text,
    String? replyId,
    String? renoteId,
    String? visibility,
  });

  Future<void> crateApiMisskeyMisskeyRustClientCreateReaction({
    required MisskeyRustClient that,
    required String noteId,
    required String reaction,
  });

  Future<String> crateApiMisskeyMisskeyRustClientGetTimeline({
    required MisskeyRustClient that,
    required String timelineType,
    required int limit,
    String? untilId,
  });

  Future<String> crateApiMisskeyMisskeyRustClientI({
    required MisskeyRustClient that,
  });

  MisskeyRustClient crateApiMisskeyMisskeyRustClientNew({
    required String host,
    required String token,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FlarumRustClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FlarumRustClient;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FlarumRustClientPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_JuheAuthClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_JuheAuthClient;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_JuheAuthClientPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MisskeyRustClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MisskeyRustClient;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MisskeyRustClientPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiFlarumFlarumRustClientClearToken({
    required FlarumRustClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlarumFlarumRustClientClearTokenConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlarumFlarumRustClientClearTokenConstMeta =>
      const TaskConstMeta(
        debugName: "FlarumRustClient_clear_token",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiFlarumFlarumRustClientGet({
    required FlarumRustClient that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFlarumFlarumRustClientGetConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlarumFlarumRustClientGetConstMeta =>
      const TaskConstMeta(
        debugName: "FlarumRustClient_get",
        argNames: ["that", "path"],
      );

  @override
  FlarumRustClient crateApiFlarumFlarumRustClientNew({
    required String baseUrl,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlarumFlarumRustClientNewConstMeta,
        argValues: [baseUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlarumFlarumRustClientNewConstMeta =>
      const TaskConstMeta(
        debugName: "FlarumRustClient_new",
        argNames: ["baseUrl"],
      );

  @override
  Future<String> crateApiFlarumFlarumRustClientPost({
    required FlarumRustClient that,
    required String path,
    required String bodyJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          sse_encode_String(bodyJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiFlarumFlarumRustClientPostConstMeta,
        argValues: [that, path, bodyJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlarumFlarumRustClientPostConstMeta =>
      const TaskConstMeta(
        debugName: "FlarumRustClient_post",
        argNames: ["that", "path", "bodyJson"],
      );

  @override
  Future<void> crateApiFlarumFlarumRustClientSetToken({
    required FlarumRustClient that,
    required String token,
    String? userId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient(
            that,
            serializer,
          );
          sse_encode_String(token, serializer);
          sse_encode_opt_String(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFlarumFlarumRustClientSetTokenConstMeta,
        argValues: [that, token, userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFlarumFlarumRustClientSetTokenConstMeta =>
      const TaskConstMeta(
        debugName: "FlarumRustClient_set_token",
        argNames: ["that", "token", "userId"],
      );

  @override
  Future<String> crateApiAuthJuheAuthClientCallbackAuth({
    required JuheAuthClient that,
    required String code,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJuheAuthClient(
            that,
            serializer,
          );
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAuthJuheAuthClientCallbackAuthConstMeta,
        argValues: [that, code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthJuheAuthClientCallbackAuthConstMeta =>
      const TaskConstMeta(
        debugName: "JuheAuthClient_callback_auth",
        argNames: ["that", "code"],
      );

  @override
  Future<String> crateApiAuthJuheAuthClientGetLoginUrl({
    required JuheAuthClient that,
    required String type,
    required String state,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJuheAuthClient(
            that,
            serializer,
          );
          sse_encode_String(type, serializer);
          sse_encode_String(state, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAuthJuheAuthClientGetLoginUrlConstMeta,
        argValues: [that, type, state],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthJuheAuthClientGetLoginUrlConstMeta =>
      const TaskConstMeta(
        debugName: "JuheAuthClient_get_login_url",
        argNames: ["that", "type", "state"],
      );

  @override
  JuheAuthClient crateApiAuthJuheAuthClientNew({
    required String appid,
    required String appkey,
    required String apiurl,
    required String callback,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(appid, serializer);
          sse_encode_String(appkey, serializer);
          sse_encode_String(apiurl, serializer);
          sse_encode_String(callback, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJuheAuthClient,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAuthJuheAuthClientNewConstMeta,
        argValues: [appid, appkey, apiurl, callback],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthJuheAuthClientNewConstMeta =>
      const TaskConstMeta(
        debugName: "JuheAuthClient_new",
        argNames: ["appid", "appkey", "apiurl", "callback"],
      );

  @override
  Future<String> crateApiAuthJuheAuthClientQueryUser({
    required JuheAuthClient that,
    required String type,
    required String socialUid,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJuheAuthClient(
            that,
            serializer,
          );
          sse_encode_String(type, serializer);
          sse_encode_String(socialUid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAuthJuheAuthClientQueryUserConstMeta,
        argValues: [that, type, socialUid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthJuheAuthClientQueryUserConstMeta =>
      const TaskConstMeta(
        debugName: "JuheAuthClient_query_user",
        argNames: ["that", "type", "socialUid"],
      );

  @override
  Future<String> crateApiMisskeyMisskeyRustClientCreateNote({
    required MisskeyRustClient that,
    String? text,
    String? replyId,
    String? renoteId,
    String? visibility,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMisskeyRustClient(
            that,
            serializer,
          );
          sse_encode_opt_String(text, serializer);
          sse_encode_opt_String(replyId, serializer);
          sse_encode_opt_String(renoteId, serializer);
          sse_encode_opt_String(visibility, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMisskeyMisskeyRustClientCreateNoteConstMeta,
        argValues: [that, text, replyId, renoteId, visibility],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMisskeyMisskeyRustClientCreateNoteConstMeta =>
      const TaskConstMeta(
        debugName: "MisskeyRustClient_create_note",
        argNames: ["that", "text", "replyId", "renoteId", "visibility"],
      );

  @override
  Future<void> crateApiMisskeyMisskeyRustClientCreateReaction({
    required MisskeyRustClient that,
    required String noteId,
    required String reaction,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMisskeyRustClient(
            that,
            serializer,
          );
          sse_encode_String(noteId, serializer);
          sse_encode_String(reaction, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMisskeyMisskeyRustClientCreateReactionConstMeta,
        argValues: [that, noteId, reaction],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMisskeyMisskeyRustClientCreateReactionConstMeta =>
      const TaskConstMeta(
        debugName: "MisskeyRustClient_create_reaction",
        argNames: ["that", "noteId", "reaction"],
      );

  @override
  Future<String> crateApiMisskeyMisskeyRustClientGetTimeline({
    required MisskeyRustClient that,
    required String timelineType,
    required int limit,
    String? untilId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMisskeyRustClient(
            that,
            serializer,
          );
          sse_encode_String(timelineType, serializer);
          sse_encode_u_32(limit, serializer);
          sse_encode_opt_String(untilId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMisskeyMisskeyRustClientGetTimelineConstMeta,
        argValues: [that, timelineType, limit, untilId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMisskeyMisskeyRustClientGetTimelineConstMeta =>
      const TaskConstMeta(
        debugName: "MisskeyRustClient_get_timeline",
        argNames: ["that", "timelineType", "limit", "untilId"],
      );

  @override
  Future<String> crateApiMisskeyMisskeyRustClientI({
    required MisskeyRustClient that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMisskeyRustClient(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMisskeyMisskeyRustClientIConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMisskeyMisskeyRustClientIConstMeta =>
      const TaskConstMeta(debugName: "MisskeyRustClient_i", argNames: ["that"]);

  @override
  MisskeyRustClient crateApiMisskeyMisskeyRustClientNew({
    required String host,
    required String token,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_String(token, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMisskeyRustClient,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMisskeyMisskeyRustClientNewConstMeta,
        argValues: [host, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMisskeyMisskeyRustClientNewConstMeta =>
      const TaskConstMeta(
        debugName: "MisskeyRustClient_new",
        argNames: ["host", "token"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FlarumRustClient => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FlarumRustClient => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_JuheAuthClient => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJuheAuthClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_JuheAuthClient => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJuheAuthClient;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MisskeyRustClient => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMisskeyRustClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MisskeyRustClient => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMisskeyRustClient;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  FlarumRustClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlarumRustClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  JuheAuthClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJuheAuthClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return JuheAuthClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MisskeyRustClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMisskeyRustClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MisskeyRustClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FlarumRustClient
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlarumRustClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FlarumRustClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlarumRustClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  JuheAuthClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJuheAuthClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return JuheAuthClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MisskeyRustClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMisskeyRustClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MisskeyRustClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FlarumRustClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlarumRustClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  JuheAuthClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJuheAuthClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return JuheAuthClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MisskeyRustClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMisskeyRustClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MisskeyRustClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  FlarumRustClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FlarumRustClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  JuheAuthClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJuheAuthClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return JuheAuthClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MisskeyRustClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMisskeyRustClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MisskeyRustClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FlarumRustClient
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FlarumRustClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FlarumRustClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FlarumRustClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  JuheAuthClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJuheAuthClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return JuheAuthClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MisskeyRustClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMisskeyRustClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MisskeyRustClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FlarumRustClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FlarumRustClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  JuheAuthClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJuheAuthClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return JuheAuthClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MisskeyRustClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMisskeyRustClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MisskeyRustClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient(
    FlarumRustClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FlarumRustClientImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJuheAuthClient(
    JuheAuthClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as JuheAuthClientImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMisskeyRustClient(
    MisskeyRustClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MisskeyRustClientImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient(
    FlarumRustClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FlarumRustClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient(
    FlarumRustClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FlarumRustClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJuheAuthClient(
    JuheAuthClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as JuheAuthClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMisskeyRustClient(
    MisskeyRustClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MisskeyRustClientImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlarumRustClient(
    FlarumRustClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FlarumRustClientImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJuheAuthClient(
    JuheAuthClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as JuheAuthClientImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMisskeyRustClient(
    MisskeyRustClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MisskeyRustClientImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class FlarumRustClientImpl extends RustOpaque implements FlarumRustClient {
  // Not to be used by end users
  FlarumRustClientImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FlarumRustClientImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_FlarumRustClient,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_FlarumRustClient,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_FlarumRustClientPtr,
  );

  Future<void> clearToken() =>
      RustLib.instance.api.crateApiFlarumFlarumRustClientClearToken(that: this);

  Future<String> get_({required String path}) => RustLib.instance.api
      .crateApiFlarumFlarumRustClientGet(that: this, path: path);

  Future<String> post({required String path, required String bodyJson}) =>
      RustLib.instance.api.crateApiFlarumFlarumRustClientPost(
        that: this,
        path: path,
        bodyJson: bodyJson,
      );

  Future<void> setToken({required String token, String? userId}) =>
      RustLib.instance.api.crateApiFlarumFlarumRustClientSetToken(
        that: this,
        token: token,
        userId: userId,
      );
}

@sealed
class JuheAuthClientImpl extends RustOpaque implements JuheAuthClient {
  // Not to be used by end users
  JuheAuthClientImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  JuheAuthClientImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_JuheAuthClient,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_JuheAuthClient,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_JuheAuthClientPtr,
  );

  Future<String> callbackAuth({required String code}) => RustLib.instance.api
      .crateApiAuthJuheAuthClientCallbackAuth(that: this, code: code);

  Future<String> getLoginUrl({required String type, required String state}) =>
      RustLib.instance.api.crateApiAuthJuheAuthClientGetLoginUrl(
        that: this,
        type: type,
        state: state,
      );

  Future<String> queryUser({required String type, required String socialUid}) =>
      RustLib.instance.api.crateApiAuthJuheAuthClientQueryUser(
        that: this,
        type: type,
        socialUid: socialUid,
      );
}

@sealed
class MisskeyRustClientImpl extends RustOpaque implements MisskeyRustClient {
  // Not to be used by end users
  MisskeyRustClientImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MisskeyRustClientImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_MisskeyRustClient,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_MisskeyRustClient,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_MisskeyRustClientPtr,
  );

  Future<String> createNote({
    String? text,
    String? replyId,
    String? renoteId,
    String? visibility,
  }) => RustLib.instance.api.crateApiMisskeyMisskeyRustClientCreateNote(
    that: this,
    text: text,
    replyId: replyId,
    renoteId: renoteId,
    visibility: visibility,
  );

  Future<void> createReaction({
    required String noteId,
    required String reaction,
  }) => RustLib.instance.api.crateApiMisskeyMisskeyRustClientCreateReaction(
    that: this,
    noteId: noteId,
    reaction: reaction,
  );

  Future<String> getTimeline({
    required String timelineType,
    required int limit,
    String? untilId,
  }) => RustLib.instance.api.crateApiMisskeyMisskeyRustClientGetTimeline(
    that: this,
    timelineType: timelineType,
    limit: limit,
    untilId: untilId,
  );

  Future<String> i() =>
      RustLib.instance.api.crateApiMisskeyMisskeyRustClientI(that: this);
}
