// This file is automatically generated. Do not edit it.

#ifndef FLUTTER_DART_DEFINES_H_
#define FLUTTER_DART_DEFINES_H_

// clang-format off

#define DART_DEFINE_ENGINE_ENTRY_POINT_NAME "DartEntryPoints"
#define DART_DEFINE_MAIN_DART "lib/main.dart"
#define DART_DEFINE_FLUTTER_ASSET_DIR_NAME "flutter_assets"
#define DART_DEFINE_FLUTTER_ICU_DATA_FILE "data/icudtl.dat"
#define DART_DEFINE_FLUTTER_LIBRARY "lib/libflutter_linux_gtk.so"

// clang-format on

#endif  // FLUTTER_DART_DEFINES_H_