// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<JuheAuthClient>>
abstract class JuheAuthClient implements RustOpaqueInterface {
  Future<String> callbackAuth({required String code});

  Future<String> getLoginUrl({required String type, required String state});

  factory JuheAuthClient({
    required String appid,
    required String appkey,
    required String apiurl,
    required String callback,
  }) => RustLib.instance.api.crateApiAuthJuheAuthClientNew(
    appid: appid,
    appkey: appkey,
    apiurl: apiurl,
    callback: callback,
  );

  Future<String> queryUser({required String type, required String socialUid});
}
