// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlarumRustClient>>
abstract class FlarumRustClient implements RustOpaqueInterface {
  Future<void> clearToken();

  Future<String> get_({required String path});

  factory FlarumRustClient({required String baseUrl}) =>
      RustLib.instance.api.crateApiFlarumFlarumRustClientNew(baseUrl: baseUrl);

  Future<String> post({required String path, required String bodyJson});

  Future<void> setToken({required String token, String? userId});
}
