// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MisskeyUser`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MisskeyRustClient>>
abstract class MisskeyRustClient implements RustOpaqueInterface {
  Future<String> createNote({
    String? text,
    String? replyId,
    String? renoteId,
    String? visibility,
  });

  Future<void> createReaction({
    required String noteId,
    required String reaction,
  });

  Future<String> getTimeline({
    required String timelineType,
    required int limit,
    String? untilId,
  });

  Future<String> i();

  factory MisskeyRustClient({required String host, required String token}) =>
      RustLib.instance.api.crateApiMisskeyMisskeyRustClientNew(
        host: host,
        token: token,
      );
}
