// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'streaming.dart';

// These functions are ignored because they are not marked as `pub`: `generate_channel_id`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MisskeyUser`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MisskeyRustClient>>
abstract class MisskeyRustClient implements RustOpaqueInterface {
  Future<void> connectStreaming();

  Future<String> createChatMessage({
    String? userId,
    String? roomId,
    String? text,
    String? fileId,
  });

  Future<String> createNote({
    String? text,
    String? replyId,
    String? renoteId,
    String? visibility,
  });

  Future<void> createReaction({
    required String noteId,
    required String reaction,
  });

  Future<void> disconnectStreaming();

  Future<String> getChatHistory({required int limit});

  Future<String> getChatMessages({
    String? userId,
    String? roomId,
    required int limit,
    String? untilId,
  });

  Future<String> getChatRooms();

  Future<int> getOnlineUsersCount();

  Future<String> getTimeline({
    required String timelineType,
    required int limit,
    String? untilId,
  });

  Future<String> i();

  bool isStreamingConnected();

  factory MisskeyRustClient({required String host, required String token}) =>
      RustLib.instance.api.crateApiMisskeyMisskeyRustClientNew(
        host: host,
        token: token,
      );

  StreamEvent? pollStreamingEvent();

  Future<void> sendStreamingMessage({required String message});

  Future<String> showUser({required String userId});

  Future<void> subscribeToMain();

  Future<void> subscribeToTimeline({required String timelineType});
}
