// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StreamEvent>>
abstract class StreamEvent implements RustOpaqueInterface {
  Value get body;

  String get channelId;

  String get eventType;

  set body(Value body);

  set channelId(String channelId);

  set eventType(String eventType);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StreamingClient>>
abstract class StreamingClient implements RustOpaqueInterface {
  Future<void> connect({required String url, required String token});

  Future<void> disconnect();

  bool isCurrentlyConnected();

  factory StreamingClient() =>
      RustLib.instance.api.crateApiStreamingStreamingClientNew();

  StreamEvent? pollEvent();

  Future<void> sendMessage({required String message});

  Future<void> subscribeToChannel({
    required String channelName,
    required String channelId,
  });

  Future<void> unsubscribeFromChannel({required String channelId});
}
